### ISSUE TITLE
JDK11 support

### ISSUE THREAD

**Issue by gschrader** [CaciocavalloSilano/caciocavallo#1]

**Comment by JoroRoss** [comment]
I tried this out in one of my projects, and am happy to report that it works rather well.  Unfortunately, I can't migrate to Java 11 fully yet, so I was wondering whether it would be possible to change the source/target that you release with to 8?  That way, the 1.11 version should work in both JDKs, which will make it much easier for clients to migrate.

**Comment by gschrader** [comment]
@JoroRoss I'm not sure I understand what you're asking. Version 1.10 works with Java 8 and version 1.11 works Java 11. They aren't interchangeable as there are API changes between the JDK versions.

**Comment by JoroRoss** [comment]
Ah I see, java.awt was totally changed as part of Jigsaw, gotcha.

What I was asking was whether it would be possible to release a single artifact that would work with both LTS releases.  I suppose, given the awt API changes, that would only be possible using a multi-version jar.

I will experiment with using maven profiles to switch between 1.10 and 1.11 based on the JDK.

**Comment by gschrader** [comment]
Having a MRJAR would be pretty nice.

**Comment by JoroRoss** [comment]
I'm happy to report that it my using profiles is relatively painless.  Having a multi-release jar would indeed be nice.

**Comment by JoroRoss** [comment]
Another question: given https://bugs.java.com/bugdatabase/view_bug.do?bug_id=8223417, will it even be possible to port this project to JDK 13 or higher?

**Comment by gschrader** [comment]
I was able to get it to work with JDK 13 by using reflection to set the toolkit. 

```
            Field toolkit = Toolkit.class.getDeclaredField("toolkit");
            toolkit.setAccessible(true);
            toolkit.set(null, new CTCToolkit());
```

There are other changes needed to make JDK 13 work, I'm not sure if I'll take it any further at this point. I wonder what carnage future JDK releases will bring 😬

**Comment by JoroRoss** [comment]
:( Maybe we should pitch official headless gui testing in the JDK.
