### ISSUE TITLE
Failure when creating RobotPeers on JDK 11.0.19

### ISSUE THREAD

**Issue by mtf90** [CaciocavalloSilano/caciocavallo#13]
With the release of JDK 11.0.19, the OpenJDK developers backported the fix for [JDK-8238936](https://bugs.openjdk.org/browse/JDK-8238936) which changed the way how RobotPeers are instantiated (see, e.g., [here](https://github.com/openjdk/jdk11u-dev/pull/1601/files#diff-a10428f40f754bb03af46faccce4afab30ea5a3f34793f6ba72f91f91815b3edL139-R139) and [here](https://github.com/openjdk/jdk11u-dev/pull/1601/files#diff-c5047f684d0b4b876788e155881f7a7d0c9ed1e09c0bc4a2b744426b4753205cL440-R498)).

The [CTCToolkit](https://github.com/CaciocavalloSilano/caciocavallo/blob/cacio-1.11/cacio-tta/src/main/java/com/github/caciocavallosilano/cacio/ctc/CTCToolkit.java#L113) uses the old approach which results in the default "Unsupported device" exception when using Robots via, e.g., the assertj-swing library (which together with cacio-tta works like a charm on Java 8, btw).

Are there any plans to address this issue and potentially release a 1.11.1 (given that the fix should hopefully only be a small update on the method's signature)?

**Comment by gschrader** [comment]
Thanks for reporting and digging into it. Yes I can have a look at creating a release for this.

**Comment by mtf90** [comment]
Thanks for the quick response and the potential outlook on a new release. Unfortunately, I don't know if the recent JDK updates introduced any further breaking changes as this is the only one I encountered yet. However, given that this affects even the most basic assertj-swing use-cases, I'm sure others may be affected by this sooner or later as well.

Let me know, if you need any further information (e.g., test-cases or else).

**Comment by gschrader** [comment]
Sorry for the delay on this, I pushed a version 1.11.1 for this, it should show up on maven central soonish

**Comment by mtf90** [comment]
Thanks for the release. The issues I ran into are gone now :).
