### ISSUE TITLE
Support for JDK 18+

### ISSUE THREAD

**Issue by janblom** [CaciocavalloSilano/caciocavallo#15]
An UnsupportedOperationException is thrown in CacioExtension.makeNonFinal() in JDK 18 and higher. 
Apparently removing the final modifier is not allowed anymore in Java 18 and higher.

I though I had a solution, but I was way too optimistic.

And thanks for the great work so far!

**Comment by gschrader** [comment]
That's unfortunate, I haven't had a chance to look at later JDKs yet and but was hoping for the best. I'll try to cycle back and have a look soon.

**Comment by janblom** [comment]
I now have a PR in preparation, still need to test it cross-platform (mac, windows), with JDK 17 and 21. Using ByteBuddy interceptors.

I should be able to let you know if all looks good to me in a few days max.

**Comment by gschrader** [comment]
Oh that's interesting, I'm keen to see it.

**Comment by janblom** [comment]
Ok, so I have taken it as far as I can, and all seems fine (JDK 17+21, Linux, Mac, Windows, also tested against the project that I use @CacioTest for: https://github.com/OHDSI/WhiteRabbit)

Would you like the PR against the master branch, or would you rather make a separate branch for it?

**Comment by gschrader** [comment]
Master is fine, nice to hear that it still works with 17

**Comment by wumpz** [comment]
+1

**Comment by gschrader** [comment]
This has been merged and released, 1.18 should appear in maven central shortly.
