### ISSUE TITLE
[question] cacio-wayland

### ISSUE THREAD

**Issue by petabyteboy** [CaciocavalloSilano/caciocavallo#6]
Hi!

I found out about the caciocavallo project while looking for a way to run Java AWT/Swing GUI programs natively on Wayland.

I backported the jdk11 changes to a version of caciocavallo that still had the cacio-wayland backend: https://github.com/petabyteboy/caciocavallo/commit/81d3254699f6caaa1e9957cae47703e0b18de870

![](https://matrix.petabyte.dev/_matrix/media/r0/download/petabyte.dev/hVPcimOCyuhzoSfIlkZBjNcJ)

I'm wondering if this project is now exclusively dedicated to headless GUI testing, or if a proposal to add a Wayland backend could be accepted.

Thanks in advance,

\- Milan

**Comment by gschrader** [comment]
Hi there, sorry for the late response. I'm open to adding this back to the project. Back in the day I believe I purged some of the code (perhaps selfishly) since I didn't really understand it and wanted to keep this project simple.

**Comment by petabyteboy** [comment]
Thanks! My question is answered. I will probably prepare a PR to re-add cacio-wayland then, but it might take a while.
