### ISSUE TITLE
SIGSEGV during test run only when running with cacio-tta

### ISSUE THREAD

**Issue by hakanai** [CaciocavalloSilano/caciocavallo#7]
I tried to integrate cacio-tta into our test suite but I get a segmentation fault during the test run.

```lang-none
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fc1e20a2322, pid=13777, tid=18377
#
# JRE version: OpenJDK Runtime Environment AdoptOpenJDK (11.0.10+9) (build 11.0.10+9)
# Java VM: OpenJDK 64-Bit Server VM AdoptOpenJDK (11.0.10+9, mixed mode, tiered, compressed oops, g1 gc, linux-amd64)
# Problematic frame:
# V  [libjvm.so+0x949322]  jni_CallStaticVoidMethod+0xf2
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport %p %s %c %d %P %E" (or dumping to /opt/data/jenkins/engine/core/engine/processing/core.13777)
#
# An error report file with more information is saved as:
# /opt/data/jenkins/engine/core/engine/processing/hs_err_pid13777.log
#
# If you would like to submit a bug report, please visit:
#   https://github.com/AdoptOpenJDK/openjdk-support/issues
#
```

I have not yet managed to reproduce the same failure locally so investigation is ongoing. My local system is macOS and doesn't appear to get the issue yet, while the build machine is running Linux. The only difference between a non-crashing build and this crashing build is the addition of cacio-tta.

cacio-tta has been configured in the Gradle build script as follows:

```groovy
    tasks.withType(Test).configureEach {
        // ...
        systemProperty 'java.awt.headless', 'false'
        systemProperty 'awt.toolkit', 'com.github.caciocavallosilano.cacio.ctc.CTCToolkit'
        systemProperty 'java.awt.graphicsenv', 'com.github.caciocavallosilano.cacio.ctc.CTCGraphicsEnvironment'
    }

    dependencies {
        // ...
        testRuntimeOnly 'com.github.caciocavallosilano:cacio-tta:1.11'
    }
```

**Comment by gschrader** [comment]
It's been awhile since I've run tests on Linux. I'll see if I can find some time to set up some GitHub actions to run the tests.

**Comment by hakanai** [comment]
It was painful to get our Docker container working, but I reproduced it in a local container, so now I have the hotspot crash log:

[hs_err_pid244.log](https://github.com/CaciocavalloSilano/caciocavallo/files/6660205/hs_err_pid244.log)

```lang-none
Stack: [0x00007ff8ea5d2000,0x00007ff8ea6d3000],  sp=0x00007ff8ea6cff70,  free space=1015k
Native frames: (J=compiled Java code, A=aot compiled Java code, j=interpreted, Vv=VM code, C=native code)
V  [libjvm.so+0x949322]  jni_CallStaticVoidMethod+0xf2
C  [libawt_xawt.so+0x3a368]  Java_sun_awt_FcFontManager_getFontPathNative+0x1f8
j  sun.awt.FcFontManager.getFontPathNative(ZZ)Ljava/lang/String;+0 java.desktop@11.0.10
j  sun.awt.X11FontManager.getFontPath(Z)Ljava/lang/String;+8 java.desktop@11.0.10
j  sun.font.SunFontManager.getPlatformFontPath(Z)Ljava/lang/String;+10 java.desktop@11.0.10
j  sun.font.SunFontManager.getPlatformFontDirs(Z)[Ljava/lang/String;+14 java.desktop@11.0.10
j  sun.font.SunFontManager.getFullNameToFileMap()Ljava/util/HashMap;+12 java.desktop@11.0.10
j  sun.font.SunFontManager.getFamilyNamesFromPlatform(Ljava/util/TreeMap;Ljava/util/Locale;)Z+1 java.desktop@11.0.10
j  sun.font.SunFontManager.getInstalledFontFamilyNames(Ljava/util/Locale;)[Ljava/lang/String;+150 java.desktop@11.0.10
j  sun.java2d.SunGraphicsEnvironment.getAvailableFontFamilyNames(Ljava/util/Locale;)[Ljava/lang/String;+6 java.desktop@11.0.10
j  sun.java2d.SunGraphicsEnvironment.getAvailableFontFamilyNames()[Ljava/lang/String;+4 java.desktop@11.0.10
j  net.sf.jasperreports.engine.util.JRGraphEnvInitializer.initializeGraphEnv()V+22
j  net.sf.jasperreports.engine.fill.BaseReportFiller.<init>(Lnet/sf/jasperreports/engine/JasperReportsContext;Lnet/sf/jasperreports/engine/fill/JasperReportSource;Lnet/sf/jasperreports/engine/fill/FillerParent;)V+9
j  net.sf.jasperreports.engine.fill.JRBaseFiller.<init>(Lnet/sf/jasperreports/engine/JasperReportsContext;Lnet/sf/jasperreports/engine/fill/JasperReportSource;Lnet/sf/jasperreports/engine/fill/BandReportFillerParent;)V+4
j  net.sf.jasperreports.engine.fill.JRVerticalFiller.<init>(Lnet/sf/jasperreports/engine/JasperReportsContext;Lnet/sf/jasperreports/engine/fill/JasperReportSource;Lnet/sf/jasperreports/engine/fill/BandReportFillerParent;)V+4
j  net.sf.jasperreports.engine.fill.JRFiller.createBandReportFiller(Lnet/sf/jasperreports/engine/JasperReportsContext;Lnet/sf/jasperreports/engine/fill/JasperReportSource;)Lnet/sf/jasperreports/engine/fill/JRBaseFiller;+65
j  net.sf.jasperreports.engine.fill.JRFiller.createReportFiller(Lnet/sf/jasperreports/engine/JasperReportsContext;Lnet/sf/jasperreports/engine/fill/JasperReportSource;)Lnet/sf/jasperreports/engine/fill/ReportFiller;+58
j  net.sf.jasperreports.engine.fill.JRFiller.fill(Lnet/sf/jasperreports/engine/JasperReportsContext;Lnet/sf/jasperreports/engine/fill/JasperReportSource;Ljava/util/Map;)Lnet/sf/jasperreports/engine/JasperPrint;+2
j  net.sf.jasperreports.engine.fill.JRFiller.fill(Lnet/sf/jasperreports/engine/JasperReportsContext;Lnet/sf/jasperreports/engine/JasperReport;Ljava/util/Map;)Lnet/sf/jasperreports/engine/JasperPrint;+6
j  net.sf.jasperreports.engine.JasperFillManager.fill(Lnet/sf/jasperreports/engine/JasperReport;Ljava/util/Map;)Lnet/sf/jasperreports/engine/JasperPrint;+6
j  net.sf.jasperreports.engine.JasperFillManager.fillReport(Lnet/sf/jasperreports/engine/JasperReport;Ljava/util/Map;)Lnet/sf/jasperreports/engine/JasperPrint;+5
j  com.acme.nrt.ReportGenerator.print()Lnet/sf/jasperreports/engine/JasperPrint;+34
j  com.acme.nrt.ReportGenerator.exportReportToByteArray(Lcom/acme/nrt/entities/ReportOutputFormat;)[B+18
j  com.acme.nrt.TestReportGenerator.testReportGenerationSucceed()V+184
```

So it seems like Jasper Reports is trying to get the font directory. It then gets as far as `Java_sun_awt_FcFontManager_getFontPathNative` which then calls back `jni_CallStaticVoidMethod`, which crashes.

**Comment by hakanai** [comment]
Initially I didn't see a call to `CallStaticVoidMethod` in `Java_sun_awt_FcFontManager_getFontPathNative`, but it calls `getPlatformFontPathChars`, which might be getting inlined. `getPlatformFontPathChars` has this call to `AWT_LOCK()` macro, which actually expands to a bunch of code, which does call `CallStaticVoidMethod`...

```c
#define AWT_LOCK_IMPL() \
    do { \
        (*env)->CallStaticVoidMethod(env, tkClass, awtLockMID); \
        if ((*env)->ExceptionCheck(env)) { \
            (*env)->ExceptionClear(env); \
        } \
    } while(0)
```

That led me to wonder whether the issue was related to multi-threading, so I changed the test to run on the EDT - and the test no longer crashed!

I also tried running headed with the default toolkit and using Xvfb instead, and that also didn't crash.

So it seems like the crash happens in this combination:

* When running the Cacio AWT implementation
* _And_ running on a thread that isn't the EDT
* _And_ making calls to font manager code (listing the fonts confirmed to cause it so far)

So for most AWT tests you would never seen this happen because they are already running on the EDT - this explains why the first test I diagnosed didn't seem to be AWT-related - it's just getting the fonts, which normally doesn't have to be done on the EDT.

**Comment by gschrader** [comment]
Interesting, yes it looks like there is some history with the font manager and on Linux based on these lines of code: 

https://github.com/CaciocavalloSilano/caciocavallo/blob/4f2e35f867915bdcdf6ee4c22c33c06fdf1fff76/cacio-shared/src/main/java/com/github/caciocavallosilano/cacio/peer/CacioToolkit.java#L90-L91

I don't know what `sun.awt.FcFontManager` was but it doesn't appear to exist anymore, so this needs to change to something, looks like there used to be a cacio implementation at one point based on the comment at the end of line code. I'll do some more digging when I can get back to this project.

**Comment by hakanai** [comment]
Oh, sun.awt.FcFontManager exists...

https://github.com/AdoptOpenJDK/openjdk-jdk11/blob/master/src/java.desktop/unix/classes/sun/awt/FcFontManager.java

But if you're searching for it on macOS JDK 11 or Windows JDK 11 you won't find it.

**Comment by gschrader** [comment]
Sorry my bad I should have read closer, I see you even had it in your crash log and refer to it in your initial analysis. I forgot each platform has different classes. I would guess that the native call must be expecting other parts of the toolkit to be the matching, maybe the lock or something. Maybe there is something that can be done but I'm glad you have a workaround for now. I have run into similar issues before not having the initialization in the EDT so it doesn't surprise me.

I'd still like to get the tests running so it can be run against newer builds of the JDK.

**Comment by gschrader** [comment]
I should have responded back on this sooner. I've encountered seg faults when another non-gui test somehow caused the JDK toolkit to be initialized before a cacio test runs. I'm going to close this issue but feel free to reopen if you think it's something else.
