### ISSUE TITLE
Support JDK 17

### ISSUE THREAD

**Issue by rabelenda** [CaciocavalloSilano/caciocavallo#8]
Hello, 

do you have plans to add support for JDK 17?

Regards

**Comment by gschrader** [comment]
Yes, I have a local branch with it working. I need to do some more testing though. I will see if I can find some more time to have a look at it.

**Comment by rabelenda** [comment]
Hello,

Any way we can help with this?

Regards

**Comment by gschrader** [comment]
I've pushed my branch, I've only tested on macOS so far. I need to figure out the process to publish to Maven central again so hopefully I can get something published soon.

**Comment by gschrader** [comment]
More changes are needed for Windows/Linux, I'm looking at that now.

**Comment by gschrader** [comment]
I think I have this working ok, tests pass anyway. I have released 1.17 and it should show up on Maven central shortly. Let me know how it goes for you.

**Comment by rabelenda** [comment]
I will give it a try and let you know, thank you very much!

**Comment by gschrader** [comment]
This has been working at my work, going to go ahead and close. Feel free to raise any follow up issues.
